version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    # environment:
    #   - DB_HOST=127.0.0.1
    #   - PORT=5439
    #   - DB_USERNAME=postgres
    env_file:
      - .env
    ports:
      - "${¡DB_PORT}"
    container_name: picassodb
    volumes:
      - ./postgres:/var/lib/postgresql/data